### ISSUE TITLE
:coffee:  "java.lang.UnsatisfiedLinkError: /tmp/libduckdb"

### ISSUE THREAD

**Issue by adriens** [rayokota/kwack#28]
Hi, I'm currently installing the whole thing from scratch, and I'm getting this : 

![image](https://github.com/user-attachments/assets/fecca8a1-7960-4707-8f0b-201933a10026)

```
ubuntu $ ./kwack/bin/kwack -F kwack/config/kwack.properties 
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libduckdb_java16765913264858272223.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/libduckdb_java16765913264858272223.so)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2450)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2506)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2705)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2635)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1854)
        at org.duckdb.DuckDBNative.<clinit>(DuckDBNative.java:58)
        at org.duckdb.DuckDBConnection.newConnection(DuckDBConnection.java:51)
        at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:41)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at io.kcache.kwack.KwackEngine.init(KwackEngine.java:187)
        at io.kcache.kwack.KwackMain.call(KwackMain.java:156)
        at io.kcache.kwack.KwackMain.call(KwackMain.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at io.kcache.kwack.KwackMain.main(KwackMain.java:299)
```

Could you be more speciic about java & duckdb install steps ?

I'll also use the default demo from : 

- #24 

If you have one... so I'll reuse it (including schema registry) so I don't have to recreate a new one from scratch.

**Comment by rayokota** [comment]
Which version of ubuntu are you using?

**Comment by rayokota** [comment]
It's likely you're using Ubuntu 20.04, which has glibc 2.31.   It looks like kwack only works with Ubuntu 22.04+

I had to build the DuckDB shared lib for linux myself, as kwack relies on some fixes in DuckDB that haven't been released yet.  I'll perhaps look into a docker-compose setup if that works for you.

**Comment by rayokota** [comment]
@adriens , please try https://github.com/rayokota/kwack/releases/tag/v0.9.0

**Comment by adriens** [comment]
> Which version of Ubuntu are you using?

Hi @rayokota , I'm running on : 
![image](https://github.com/user-attachments/assets/534e70a5-034c-48a6-8872-4bbf85cf39cd)

**Comment by adriens** [comment]
:pray: for the release, I'll give it a try and give you feedback.
:thinking: do you plan to sahre about : 
- #24 
 ?
